import json
import os
import sys
from pathlib import Path

# Paths
script_dir = Path(__file__).parent
project_root = script_dir.parent
package_json_path = project_root / "package.json"
repo_dir = project_root / "docs"
index_json_path = repo_dir / "index.json"

# Basic repo info
REPO_NAME = "UE-Style Transform Gizmo"
REPO_AUTHOR = "NerArth"
BASE_URL = "https://nerarth.github.io/VRC_UnrealTransformGizmo"

def main():
    if not package_json_path.exists():
        print(f"Error: package.json not found at {package_json_path}")
        sys.exit(1)

    if not repo_dir.exists():
        os.makedirs(repo_dir)

    with open(package_json_path, "r") as f:
        package_data = json.load(f)

    # Load existing index.json or create new
    if index_json_path.exists():
        with open(index_json_path, "r") as f:
            index_data = json.load(f)
    else:
        index_data = {
            "name": REPO_NAME,
            "author": REPO_AUTHOR,
            "url": f"{BASE_URL}/index.json",
            "packages": {}
        }

    package_id = package_data["name"]
    version = package_data["version"]

    # Calculate SHA256 of the zip (it should have been generated by automated_package.py)
    zip_name = f"{package_id}-{version}.zip"
    zip_path = project_root / ".dev" / "Releases" / zip_name
    sha_path = zip_path.with_suffix(".zip.sha256")

    if not zip_path.exists() or not sha_path.exists():
        print(f"Error: Zip/Hash not found in .dev/Releases/ for {version}. Run automated_package.py first.")
        sys.exit(1)

    with open(sha_path, "r") as f:
        sha256 = f.read().strip()

    # Build manifest for this version
    # Point to GitHub Releases download URL
    manifest = package_data.copy()
    manifest["url"] = f"https://github.com/NerArth/VRC_UnrealTransformGizmo/releases/download/v{version}/{zip_name}"
    manifest["sha256"] = sha256

    # Update index
    if package_id not in index_data["packages"]:
        index_data["packages"][package_id] = {"versions": {}}
    
    index_data["packages"][package_id]["versions"][version] = manifest

    # Save index.json
    with open(index_json_path, "w") as f:
        json.dump(index_data, f, indent=4)

    print(f"Successfully updated VPM index at {index_json_path} for version {version}")

if __name__ == "__main__":
    main()
